export const productsData = [
  {
    name: 'Lumina Selene Hand-Textured Moon Wall Clock',
    slug: 'lumina-selene-moon-wall-clock',
    description: 'Crafted over 18 artisan hours, the Lumina Selene captures the cratered topography of the moon. Built with lightweight mineral plaster, hand-pigmented charcoal dust, and gilded 24K gold leaf lunar phase accents. Equipped with an ultra-quiet German sweep quartz movement so your gallery wall remains peaceful.',
    shortDescription: 'Hand-sculpted lunar crater texture with 24k gold leaf accents and silent quartz sweep.',
    category: 'Moon Clock',
    price: 18500,
    discountPrice: 16500,
    compareAtPrice: 22000,
    images: ['/img1.jpg', '/img2.webp', '/img13.jpeg'],
    colors: ['Warm Ivory', 'Charcoal Grey', 'Gold Trim'],
    material: 'Mineral Composite Plaster & 24K Gold Leaf',
    materials: ['Mineral Composite Plaster', '24K Gold Leaf Trim', 'German Silent Sweep Quartz', 'Brushed Brass Hands'],
    dimensions: '45 cm (17.7") Diameter x 4 cm Depth',
    stock: 8,
    isFeatured: true,
    isLimitedEdition: false,
    ratings: 4.9,
    numReviews: 42,
    badges: ['Handmade', 'Bestseller'],
  },
  {
    name: 'White and Gold Moon Clock',
    slug: 'white-and-gold-moon-clock',
    description: 'A luminous statement piece blending alabaster white stone relief with hand-hammered 24K gold leaf crescents. Each celestial crater is sculpted by hand, reflecting ambient room lighting with unmatched luxury.',
    shortDescription: 'Alabaster white stone relief with radiant hand-gilded 24k gold leaf accents.',
    category: 'Moon Clock',
    price: 24500,
    discountPrice: 21900,
    compareAtPrice: 28000,
    images: ['/img2.webp', '/img1.jpg', '/img3.jpeg'],
    colors: ['Pure White', 'Gilded Gold'],
    material: 'Natural Alabaster Gypsum & Gold Foil',
    materials: ['Alabaster Gypsum', 'Gold Foil Leaf', 'Precision Silent Motor'],
    dimensions: '50 cm (19.7") Diameter x 4.5 cm Depth',
    stock: 6,
    isFeatured: true,
    isLimitedEdition: false,
    ratings: 5.0,
    numReviews: 28,
    badges: ['Handmade', 'Featured'],
  },
  {
    name: 'Midnight Resin Moon Clock',
    slug: 'midnight-resin-moon-clock',
    description: 'Deep cosmic indigo resin meets raw moon rock textures. Layers of deep celestial pigments, stardust mica powder, and shimmering liquid gold veins create a night sky effect that enchants any room.',
    shortDescription: 'Cosmic indigo resin poured over tactile lunar textures with liquid gold veins.',
    category: 'Moon Clock',
    price: 21000,
    discountPrice: 0,
    compareAtPrice: 25000,
    images: ['/img3.jpeg', '/img1.jpg'],
    colors: ['Midnight Blue', 'Stardust Mica', 'Gold'],
    material: 'Epoxy Resin & Mineral Bas-Relief',
    materials: ['Artisan Epoxy Resin', 'Mica Powder', 'Bas-Relief Plaster', 'Brass Hands'],
    dimensions: '40 cm (15.7") Diameter x 3.5 cm Depth',
    stock: 12,
    isFeatured: false,
    isLimitedEdition: false,
    ratings: 4.8,
    numReviews: 19,
    badges: ['Handmade', 'New Arrival'],
  },
  {
    name: 'Natural Oak Minimal Clock',
    slug: 'natural-oak-minimal-clock',
    description: 'Milled from sustainably sourced European White Oak, this minimalist clock showcases raw organic wood grain preserved with natural Danish oil. Sleek recessed hour markers and brass hands offer subtle architectural charm.',
    shortDescription: 'Solid European White Oak with hand-rubbed oil finish and recessed index markers.',
    category: 'Wooden Clock',
    price: 15500,
    discountPrice: 13900,
    compareAtPrice: 18000,
    images: ['/img4.png', '/img5.webp'],
    colors: ['Natural Honey Oak', 'Matte Black Hands'],
    material: 'Solid European White Oak',
    materials: ['Solid Oak', 'Danish Wood Oil', 'Japanese Silent Sweep Movement'],
    dimensions: '38 cm (15.0") Diameter x 3 cm Depth',
    stock: 15,
    isFeatured: false,
    isLimitedEdition: false,
    ratings: 4.9,
    numReviews: 35,
    badges: ['Handmade', 'Organic Wood'],
  },
  {
    name: 'Ivory Wooden Sunburst Clock',
    slug: 'ivory-wooden-sunburst-clock',
    description: 'Intricately hand-carved radiating rays inspired by mid-century horology, finished in warm ivory lacquer with gilded edges. An iconic focal point for contemporary living rooms and executive suites.',
    shortDescription: 'Hand-carved radial sunburst geometry with warm ivory lacquer and gold tips.',
    category: 'Wooden Clock',
    price: 26000,
    discountPrice: 23500,
    compareAtPrice: 30000,
    images: ['/img5.webp', '/img4.png'],
    colors: ['Warm Ivory', 'Brushed Brass'],
    material: 'Solid Ash Wood & Brass Inlays',
    materials: ['Ash Wood', 'Satin Lacquer', 'Brass Hour Markers'],
    dimensions: '60 cm (23.6") Diameter x 5 cm Depth',
    stock: 5,
    isFeatured: true,
    isLimitedEdition: false,
    ratings: 4.95,
    numReviews: 22,
    badges: ['Handmade', 'Statement Piece'],
  },
  {
    name: 'White Marble Resin Clock',
    slug: 'white-marble-resin-clock',
    description: 'Fluid pour of Carrara-inspired white epoxy resin accented with soft grey swirls and crystalline metallic gold inclusions. Diamond-polished to a high-gloss museum glass finish.',
    shortDescription: 'Carrara marble aesthetic created through multi-layered artisan epoxy pour.',
    category: 'Resin Clock',
    price: 19500,
    discountPrice: 17500,
    compareAtPrice: 23000,
    images: ['/img7.jpeg', '/img8.jpeg'],
    colors: ['Carrara White', 'Smoky Grey', 'Gold Flakes'],
    material: 'Crystal Epoxy Resin & MDF Substrate',
    materials: ['Crystal Clear Epoxy', 'Gold Leaf Flakes', 'Silent Quartz Movement'],
    dimensions: '42 cm (16.5") Diameter x 3 cm Depth',
    stock: 9,
    isFeatured: false,
    isLimitedEdition: false,
    ratings: 4.85,
    numReviews: 31,
    badges: ['Handmade', 'Bestseller'],
  },
  {
    name: 'Pearl Resin Galaxy Clock',
    slug: 'pearl-resin-galaxy-clock',
    description: 'Iridescent mother-of-pearl pigments shift dynamically across this mesmerizing timepiece. Hand-poured resin creates swirling nebula vortexes punctuated by slim golden needle hands.',
    shortDescription: 'Shifting mother-of-pearl resin nebula with floating metallic indices.',
    category: 'Resin Clock',
    price: 22500,
    discountPrice: 0,
    compareAtPrice: 26000,
    images: ['/img8.jpeg', '/img7.jpeg'],
    colors: ['Pearlescent Silver', 'Champagne Gold'],
    material: 'Multi-layer Epoxy Resin',
    materials: ['Pearl Mica Resin', 'Polished Brass Rim', 'Silent Quartz Mechanism'],
    dimensions: '45 cm (17.7") Diameter x 3.5 cm Depth',
    stock: 7,
    isFeatured: false,
    isLimitedEdition: false,
    ratings: 4.9,
    numReviews: 17,
    badges: ['Handmade', 'Artisanal Resin'],
  },
  {
    name: 'Gold Orbit Statement Clock',
    slug: 'gold-orbit-statement-clock',
    description: 'An architectural horological masterpiece. Three concentric open brass rings orbit around a floating marble and walnut core. Precision calibrated counterweights ensure silent, effortless balance.',
    shortDescription: 'Concentric brass orbital rings with a suspended floating core.',
    category: 'Luxury Statement Clock',
    price: 38000,
    discountPrice: 34500,
    compareAtPrice: 45000,
    images: ['/img12.jpeg', '/img11.jpeg'],
    colors: ['Satin Brushed Gold', 'Matte Charcoal'],
    material: 'Solid Brass & American Walnut',
    materials: ['Solid Brass Rings', 'Solid American Walnut', 'German Engineered Movement'],
    dimensions: '75 cm (29.5") Diameter x 6 cm Depth',
    stock: 4,
    isFeatured: true,
    isLimitedEdition: false,
    ratings: 5.0,
    numReviews: 14,
    badges: ['Handmade', 'Luxury Statement'],
  },
  {
    name: 'Minimal Cream and Gold Clock',
    slug: 'minimal-cream-and-gold-clock',
    description: 'Pure understated elegance. A brushed cream matte ceramic-textured face with ultra-fine golden dial accents and custom tapered hands. Designed for tranquil, modern interiors.',
    shortDescription: 'Understated matte cream face with ultra-fine golden accents and silent sweep.',
    category: 'Minimalist Clock',
    price: 14000,
    discountPrice: 12500,
    compareAtPrice: 16500,
    images: ['/img10.jpeg', '/img9.jpeg'],
    colors: ['Matte Cream', 'Brushed Gold'],
    material: 'Ceramic Composite & Brushed Brass',
    materials: ['Ceramic Composite', 'Brushed Brass Dial', 'Non-Ticking Mechanism'],
    dimensions: '35 cm (13.8") Diameter x 2.8 cm Depth',
    stock: 18,
    isFeatured: false,
    isLimitedEdition: false,
    ratings: 4.8,
    numReviews: 29,
    badges: ['Handmade', 'Minimalist'],
  },
  {
    name: 'Limited-Edition Lunar Eclipse Clock',
    slug: 'limited-edition-lunar-eclipse-clock',
    description: 'Serialized collector edition with only 50 pieces hand-crafted worldwide. Features a dramatic obsidian black plaster eclipse boundary meeting a luminescent 24K gold foil corona. Certificate of Authenticity signed by master horologist included.',
    shortDescription: 'Numbered collector edition showcasing an obsidian eclipse and 24K gold corona.',
    category: 'Limited Edition',
    price: 48000,
    discountPrice: 0,
    compareAtPrice: 55000,
    images: ['/img13.jpeg', '/img1.jpg', '/img2.webp'],
    colors: ['Obsidian Black', '24K Gilded Gold'],
    material: 'Obsidian Mineral Plaster & 24K Gold Leaf',
    materials: ['Volcanic Plaster', '24K Gold Foil Corona', 'High-Torque German Movement'],
    dimensions: '55 cm (21.7") Diameter x 5 cm Depth',
    stock: 3,
    isFeatured: true,
    isLimitedEdition: true,
    ratings: 5.0,
    numReviews: 8,
    badges: ['Limited Edition', 'Certified 1 of 50', 'Collector Item'],
  },
];

export const categoriesData = [
  {
    name: 'Moon Clock',
    slug: 'moon-clocks',
    description: 'Artisanal timepieces capturing the texture, luminous radiance, and celestial rhythm of lunar surfaces.',
    image: '/img1.jpg',
  },
  {
    name: 'Wooden Clock',
    slug: 'wooden-clocks',
    description: 'Hand-carved from solid black walnut, sustainable oak, and aged olive wood with natural grain storytelling.',
    image: '/img4.png',
  },
  {
    name: 'Resin Clock',
    slug: 'resin-art-clocks',
    description: 'Hand-poured crystal epoxy resin blended with metallic gold leaf and fluid ocean or river patterns.',
    image: '/img7.jpeg',
  },
  {
    name: 'Minimalist Clock',
    slug: 'minimalist-clocks',
    description: 'Clean architectural silhouettes, brushed metallic accents, and refined silent sweep hands for contemporary spaces.',
    image: '/img10.jpeg',
  },
  {
    name: 'Luxury Statement Clock',
    slug: 'luxury-statement-clocks',
    description: 'Grand scale horology showpieces crafted with brass, hand-gilded 24k gold leaf, and rare natural materials.',
    image: '/img12.jpeg',
  },
  {
    name: 'Limited Edition',
    slug: 'limited-edition',
    description: 'Numbered, serialized masterworks produced in strictly limited artisanal batches.',
    image: '/img13.jpeg',
  },
];
