export const categoriesData = [
  {
    name: 'Moon Clocks',
    slug: 'moon-clocks',
    description: 'Artisanal timepieces capturing the texture, luminous radiance, and celestial rhythm of lunar surfaces.',
    image: '/img1.jpg',
    itemCount: 3,
  },
  {
    name: 'Wooden Clocks',
    slug: 'wooden-clocks',
    description: 'Hand-carved from solid black walnut, sustainable oak, and aged olive wood with natural grain storytelling.',
    image: '/img4.png',
    itemCount: 3,
  },
  {
    name: 'Resin Art Clocks',
    slug: 'resin-art-clocks',
    description: 'Hand-poured crystal epoxy resin blended with metallic gold leaf and fluid ocean or river patterns.',
    image: '/img7.jpeg',
    itemCount: 3,
  },
  {
    name: 'Minimalist Clocks',
    slug: 'minimalist-clocks',
    description: 'Clean architectural silhouettes, brushed metallic accents, and refined silent sweep hands for contemporary spaces.',
    image: '/img10.jpeg',
    itemCount: 2,
  },
  {
    name: 'Luxury Statement Clocks',
    slug: 'luxury-statement-clocks',
    description: 'Grand scale horology showpieces crafted with brass, hand-gilded 24k gold leaf, and rare natural materials.',
    image: '/img12.jpeg',
    itemCount: 2,
  },
];

export const productsData = [
  {
    _id: '64f100010000000000000001',
    name: 'Lumina Selene Hand-Textured Moon Wall Clock',
    slug: 'lumina-selene-moon-wall-clock',
    description: 'Crafted over 18 artisan hours, the Lumina Selene captures the cratered topography of the moon. Built with lightweight mineral plaster, hand-pigmented charcoal dust, and gilded 24K gold leaf lunar phase accents. Equipped with an ultra-quiet German sweep quartz movement so your gallery wall remains peaceful.',
    shortDescription: 'Hand-sculpted lunar crater texture with 24k gold leaf accents and silent quartz sweep.',
    category: 'Moon Clocks',
    price: 18500,
    compareAtPrice: 22000,
    images: [
      '/img1.jpg',
      '/img2.webp',
      '/img13.jpeg',
    ],
    materials: ['Mineral Composite Plaster', '24K Gold Leaf Trim', 'German Silent Sweep Quartz', 'Brushed Brass Hands'],
    dimensions: '45 cm (17.7") Diameter x 4 cm Depth',
    color: 'Soft Warm Ivory & Gold',
    stock: 8,
    rating: 4.95,
    reviewCount: 42,
    badges: ['Handmade', 'Bestseller', 'Limited Edition'],
    isFeatured: true,
    isLimitedEdition: true,
    movementType: 'German Silent Quartz Sweep (0dB Silent)',
    warrantyYears: 3,
  },
  {
    _id: '64f100010000000000000002',
    name: 'Aethel Luminescent Dark Moon Horology',
    slug: 'aethel-luminescent-dark-moon-clock',
    description: 'Deep volcanic basalt grey textures meet hand-carved crater detailing in this dramatic moon-phase wall timepiece. Includes subtle luminous moon dust particles around the periphery that emit a soft ambient glow under dim evening light.',
    shortDescription: 'Volcanic slate texture with subtle night luminosity and solid brass hands.',
    category: 'Moon Clocks',
    price: 21000,
    compareAtPrice: 25000,
    images: [
      '/img2.webp',
      '/img1.jpg',
      '/img3.png',
    ],
    materials: ['Basalt Mineral Clay', 'Luminescent Photoluminescent Pigment', 'Solid Brass Hands'],
    dimensions: '50 cm (19.7") Diameter x 4.5 cm Depth',
    color: 'Charcoal Basalt & Gold',
    stock: 5,
    rating: 4.88,
    reviewCount: 29,
    badges: ['Handmade', 'Limited Edition'],
    isFeatured: true,
    isLimitedEdition: true,
    movementType: 'Silent Sweep Quartz',
    warrantyYears: 2,
  },
  {
    _id: '64f100010000000000000003',
    name: 'Céleste Crescent Gilding Moon Clock',
    slug: 'celeste-crescent-gilding-moon-clock',
    description: 'A striking asymmetrical wall clock representing the golden crescent moon. Features hand-burnished warm gold leaf against a soft cream matte ceramic disc. Perfect for modern living rooms and master suites.',
    shortDescription: 'Asymmetrical golden crescent design with hand-burnished brass and cream ceramic.',
    category: 'Moon Clocks',
    price: 16500,
    compareAtPrice: 19500,
    images: [
      '/img3.png',
      '/img1.jpg',
      '/img2.webp',
    ],
    materials: ['Ceramic Composite', 'Burnished Gold Leaf', 'Silent Quartz Movement'],
    dimensions: '40 cm (15.7") Diameter',
    color: 'Warm Ivory & Metallic Gold',
    stock: 12,
    rating: 4.9,
    reviewCount: 18,
    badges: ['Handmade', 'New'],
    isFeatured: false,
    isLimitedEdition: false,
    movementType: 'Silent Sweep Quartz',
    warrantyYears: 2,
  },
  {
    _id: '64f100010000000000000004',
    name: 'Artisan Black Walnut Segmented Clock',
    slug: 'artisan-black-walnut-segmented-clock',
    description: 'Precision hand-cut segments of sustainably sourced American Black Walnut arranged in a radial grain pattern. Sealed with natural beeswax and organic hard-wax oil, highlighted by minimalist brass hour markers.',
    shortDescription: 'Radial American black walnut segments with brass inlay hour markers.',
    category: 'Wooden Clocks',
    price: 17500,
    compareAtPrice: 21000,
    images: [
      '/img4.png',
      '/img5.webp',
      '/img6.jpeg',
    ],
    materials: ['Solid American Black Walnut', 'Inlaid Brass Bar Markers', 'Beeswax Finish'],
    dimensions: '40 cm (15.7") Diameter',
    color: 'Rich Deep Walnut & Gold',
    stock: 10,
    rating: 4.92,
    reviewCount: 36,
    badges: ['Handmade', 'Bestseller'],
    isFeatured: true,
    isLimitedEdition: false,
    movementType: 'Silent Sweep Quartz',
    warrantyYears: 2,
  },
  {
    _id: '64f100010000000000000005',
    name: 'Scandinavian Live-Edge Oak Wall Horology',
    slug: 'scandinavian-live-edge-oak-clock',
    description: 'Each piece is entirely unique, retaining the organic bark edge of centuries-old European white oak. Sanded to a silky satin feel and paired with slim matte black floating hands.',
    shortDescription: 'One-of-a-kind live-edge European white oak slab with minimalist hands.',
    category: 'Wooden Clocks',
    price: 19500,
    compareAtPrice: 23500,
    images: [
      '/img5.webp',
      '/img4.png',
      '/img6.jpeg',
    ],
    materials: ['European Live-Edge Oak', 'Matte Black Anodized Aluminum Hands'],
    dimensions: '42 cm x 38 cm Natural Organic Oval',
    color: 'Natural Honey Oak',
    stock: 6,
    rating: 4.87,
    reviewCount: 22,
    badges: ['Handmade', 'Limited Edition'],
    isFeatured: false,
    isLimitedEdition: true,
    movementType: 'Silent Sweep Quartz',
    warrantyYears: 2,
  },
  {
    _id: '64f100010000000000000006',
    name: 'Olive Wood & Brushed Brass Geometric Clock',
    slug: 'olive-wood-brass-geometric-clock',
    description: 'Exquisite wild Mediterranean olive wood characterized by intense dark swirling grain lines. Embedded within an architectural circular frame of brushed metallic brass.',
    shortDescription: 'Wild Mediterranean olive wood grain within a heavy brushed brass ring.',
    category: 'Wooden Clocks',
    price: 22500,
    compareAtPrice: 27000,
    images: [
      '/img6.jpeg',
      '/img4.png',
      '/img5.webp',
    ],
    materials: ['Mediterranean Olive Wood', 'Solid Brushed Brass Frame'],
    dimensions: '48 cm (18.9") Diameter',
    color: 'Warm Golden Olive & Brass',
    stock: 7,
    rating: 4.96,
    reviewCount: 15,
    badges: ['Handmade', 'New'],
    isFeatured: false,
    isLimitedEdition: false,
    movementType: 'Silent Sweep Quartz',
    warrantyYears: 2,
  },
  {
    _id: '64f100010000000000000007',
    name: 'Emerald Gold River Resin Wall Clock',
    slug: 'emerald-gold-river-resin-wall-clock',
    description: 'A mesmerizing river of deep emerald crystal epoxy resin poured between two slabs of natural burr walnut. Infused with metallic gold mica powders that catch daylight with shimmering brilliance.',
    shortDescription: 'Hand-poured emerald resin river with metallic gold mica and live-edge walnut.',
    category: 'Resin Art Clocks',
    price: 24500,
    compareAtPrice: 29000,
    images: [
      '/img7.jpeg',
      '/img8.jpeg',
      '/img9.jpeg',
    ],
    materials: ['Burr Walnut Hardwood', 'High-Clarity Epoxy Resin', 'Gold Pigment Flakes'],
    dimensions: '45 cm (17.7") Diameter',
    color: 'Deep Emerald & Warm Gold',
    stock: 4,
    rating: 4.98,
    reviewCount: 31,
    badges: ['Handmade', 'Bestseller', 'Limited Edition'],
    isFeatured: true,
    isLimitedEdition: true,
    movementType: 'Silent Sweep Quartz',
    warrantyYears: 3,
  },
  {
    _id: '64f100010000000000000008',
    name: 'Celestial Nebula Deep Blue Epoxy Clock',
    slug: 'celestial-nebula-deep-blue-epoxy-clock',
    description: 'Inspired by interstellar gas clouds, this clock features 5 layers of multi-depth translucent dark navy, indigo, and gold glitter resin over a circular wood base.',
    shortDescription: 'Multi-layer cosmic galaxy resin design with celestial gold hour dots.',
    category: 'Resin Art Clocks',
    price: 19500,
    compareAtPrice: 23000,
    images: [
      '/img8.jpeg',
      '/img7.jpeg',
      '/img9.jpeg',
    ],
    materials: ['Epoxy Resin Art', 'Birch Wood Substrate', 'Gold Brass Markers'],
    dimensions: '40 cm (15.7") Diameter',
    color: 'Midnight Navy & Metallic Gold',
    stock: 9,
    rating: 4.85,
    reviewCount: 19,
    badges: ['Handmade'],
    isFeatured: false,
    isLimitedEdition: false,
    movementType: 'Silent Sweep Quartz',
    warrantyYears: 2,
  },
  {
    _id: '64f100010000000000000009',
    name: 'Sunburst Amber & Gold Leaf Resin Clock',
    slug: 'sunburst-amber-gold-leaf-resin-clock',
    description: 'Warm golden amber resin swirls infused with genuine 24k gold leaf foil flakes radiating from the center like sunlight through stained glass.',
    shortDescription: 'Golden amber swirl resin art with genuine 24k gold leaf foil flakes.',
    category: 'Resin Art Clocks',
    price: 21500,
    compareAtPrice: 25500,
    images: [
      '/img9.jpeg',
      '/img7.jpeg',
      '/img8.jpeg',
    ],
    materials: ['Amber Tinted Resin', '24K Gold Leaf Foil', 'High Gloss Polish'],
    dimensions: '42 cm (16.5") Diameter',
    color: 'Amber Gold & Warm Ivory',
    stock: 6,
    rating: 4.91,
    reviewCount: 14,
    badges: ['Handmade', 'New'],
    isFeatured: false,
    isLimitedEdition: false,
    movementType: 'Silent Sweep Quartz',
    warrantyYears: 2,
  },
  {
    _id: '64f100010000000000000010',
    name: 'Aura Brass Ring Minimalist Wall Clock',
    slug: 'aura-brass-ring-minimalist-wall-clock',
    description: 'An architectural floating skeleton clock consisting of an ultra-thin 50cm spun brass hoop with a suspended center walnut heart housing the silent quartz engine.',
    shortDescription: 'Floating brass hoop skeleton frame with suspended center wood core.',
    category: 'Minimalist Clocks',
    price: 14500,
    compareAtPrice: 17500,
    images: [
      '/img10.jpeg',
      '/img11.jpeg',
      '/img12.jpeg',
    ],
    materials: ['Spun Satin Brass Ring', 'Walnut Engine Core', 'Ultra-Slim Hands'],
    dimensions: '50 cm (19.7") Diameter',
    color: 'Brushed Gold & Walnut',
    stock: 14,
    rating: 4.89,
    reviewCount: 48,
    badges: ['Handmade', 'Bestseller'],
    isFeatured: true,
    isLimitedEdition: false,
    movementType: 'Silent Sweep Quartz',
    warrantyYears: 2,
  },
  {
    _id: '64f100010000000000000011',
    name: 'Matte Charcoal & Gold Wire Minimalist Clock',
    slug: 'matte-charcoal-gold-wire-minimalist-clock',
    description: 'Pure understated luxury. A matte charcoal powder-coated aluminum disk featuring delicate geometric gold wire hour indicators.',
    shortDescription: 'Powder-coated matte charcoal metal face with delicate gold wire markers.',
    category: 'Minimalist Clocks',
    price: 12500,
    compareAtPrice: 15000,
    images: [
      '/img11.jpeg',
      '/img10.jpeg',
      '/img12.jpeg',
    ],
    materials: ['Powder-Coated Aluminum', 'Gold-Plate Wire Accent Lines'],
    dimensions: '38 cm (15") Diameter',
    color: 'Charcoal & Metallic Gold',
    stock: 11,
    rating: 4.83,
    reviewCount: 23,
    badges: ['Handmade'],
    isFeatured: false,
    isLimitedEdition: false,
    movementType: 'Silent Sweep Quartz',
    warrantyYears: 2,
  },
  {
    _id: '64f100010000000000000012',
    name: 'Grand Sovereign Oversized Gold Leaf Horology',
    slug: 'grand-sovereign-oversized-gold-leaf-clock',
    description: 'The pinnacle of luxury wall art. Measuring a majestic 70cm in diameter, this statement clock features 24k gold leaf gilding over hand-carved mahogany radial sunbeams.',
    shortDescription: 'Majestic 70cm statement piece with 24k gold leaf gilded mahogany sunbeams.',
    category: 'Luxury Statement Clocks',
    price: 38500,
    compareAtPrice: 45000,
    images: [
      '/img12.jpeg',
      '/img13.jpeg',
      '/img1.jpg',
    ],
    materials: ['Hand-Carved Mahogany', '24K Italian Gold Leaf Gilded Surface', 'Heavy-Duty Brass Mechanism'],
    dimensions: '70 cm (27.5") Diameter x 5 cm Depth',
    color: 'Luminous Metallic Gold',
    stock: 3,
    rating: 5.0,
    reviewCount: 16,
    badges: ['Handmade', 'Limited Edition'],
    isFeatured: true,
    isLimitedEdition: true,
    movementType: 'High-Torque German Silent Sweep Quartz',
    warrantyYears: 5,
  },
];
